README.md
src/bowser.js
src/useragents.js

Resolves #98
This adds a property for the browser's operating system to the results object. A couple notes:
* I changed `chromeBook` to `chromeos` as `CrOS` will match things like chrome*boxes* in addition to chromebooks and I think it makes sense in this case to reflect the OS rather than the hardware (the only other place this is done is with iPad/iPod/iPhone). Kept `chromeBook` for backwards compat.
* Use `linux` for traditional desktop linux systems and leaves the specific vendor names like `android`, `chromeos`, `sailfish`, etc. for those projects that are just built on the kernel and don't use traditional gtk, etc.
* Use `windows` for windows UAs that aren't windows phone
* Hoisted up a bunch of the regexes. Getting the feeling that the creation of the results object could be broken …

Expose the UA's os as a property on the results

---

src/bowser.js
src/useragents.js

On nexus 9 for instance we detect the device as a mobile instead of a tablet which cause an error in our UX

fix nexus 7 to 9 considered as a mobile

---

src/bowser.js
test/test.js

As far as I can tell, there is some issue with the logic in `isUnsupportedBrowser`. First red flag is that if `strictMode` is true, then the `isUnsupportedBrowser` will always return true -- there are only two return statements: [the first](https://github.com/nirrattner/bowser/blob/master/src/bowser.js#L528) is always true and the [the second](https://github.com/nirrattner/bowser/blob/master/src/bowser.js#L533) is `strictMode`. Additionally, the tests didn't cover the case where there is a minimum version specified, the version requirement is met, and `strictMode` is true. This test case, which I added here, fails without any of other changes, though it seems to me this case should have the browser pass.

Fix strict mode logic

---

src/bowser.js
src/useragents.js

Some User-Agents are flagged as both `windowsphone` and `android` in some situations (example https://github.com/ded/bowser/issues/167).
This PR ensures that we don't add the `android` flag when `windowsphone` is already present.
Closes #167

fix windowsphone flagged as android

---

src/bowser.js
src/useragents.js

Same issue as in https://github.com/ded/bowser/issues/167 when `like iPhone` is present in the _User Agent_.
Related to !168

Fix WindowsPhone flagged as iOS

---

src/bowser.js

Fixes errors like `default.js:19467 Uncaught TypeError: Cannot set property 'bowser' of undefined(…)` when including files like (it's gulp-include):
```js
(function () {
//= require /path/to/bowser.js
}).call(window);
```

fix global exports

---

README.md

Hi.
I had mistaken that "`bowser()` is callable" , but in fact, `bowser` is not callable.

Fix api section 

---

package.json
src/parser.js
test/unit/parser.js

Issue #274
I'm waiting for feedback. I'm not sure about using `indexOf` which is not supported but ie8. Though, I don't know which browsers should be supported by this library.

Support non strict equality in satisfies method

---

README.md
src/parser-os.js
src/parser-platforms.js
src/utils.js
test/acceptance/useragentstrings.yml

Added **os.versionName** support for Android
*    1.5 - Cupcake
*    1.6 - Donut
*    2.0 - Eclair
*    2.1 - Eclair
*    2.2 - Froyo
*    2.x - Gingerbread
*    3.x - Honeycomb
*    4.0 - Ice Cream Sandwich
*    4.1 - Jelly Bean
*    4.4 - KitKat
*    5.x - Lollipop
*    6.x - Marshmallow
*    7.x - Nougat
*    8.x - Oreo
*    9.x - ?
Added **platform.vendor** and  **platform.model** support for Huawei Nova
`Mozilla/5.0 (Linux; Android 7.0; HUAWEI CAN-L01) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36`

Support Android version names, Recognise Huawei devices

---

.travis.yml
README.md
index.d.ts
package.json

This PR refers to issue #272, about the integration of typescript typings for v2.
TL;DR:
The typings work if we write at the bottom of the typings `export = Bowser` and `import Bowser = require("bowser")` in our code.
If we try with `import Bowser from "bowser"` and `export Bowser` or `export default Bowser` (last one as it should be), we get a false-working typings: on compiling with Webpack+Typescript, we get working typings but broken app on compilation phase.
`import Bowser = require("bowser")` seems to be supported only for retro-compatibility with older typescript versions and seems to be setted as deprecated. We have to investigate on this.

Added typings for v2

---

src/parser-browsers.js
src/parser-platforms.js
test/acceptance/useragentstrings.yml

Got two new user agent strings for the Googlebot, added tests and support for them.
`Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
`Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Safari/537.36`
I had to reorder the position of the Googlebot test to prevent the platform browser being incorrectly detected as an unknown os Safari browser.
Also added new platform type "bot".

Added support for Googlebot recognition

---

README.md
index.d.ts

I'm creating this PR to correct the Readme, because v2 was published without removing references to it as an alpha version, and to correct broken indentation for typings made by me.
I hope you appreciate! 😊

Fixed typings indentation and edited readme

---

src/parser.js
test/unit/parser.js

This patch adds the isEngine API call (and getEngineName to support it).  This will make the code cleaner in my app.

Add getEngineName and isEngine API calls

---

src/parser-browsers.js
src/parser-os.js
src/parser-platforms.js
test/acceptance/useragentstrings.yml

Adds support for the PlayStation 4 webkit user agent string.
Wasn't sure what to do for platform since it doesn't really fit into the other categories so I added tv. If anyone has a better suggestion, willing to change that.

Add PlayStation 4 browser support

---

.eslintrc.yml
package-lock.json
src/bowser.js
src/parser-browsers.js
src/parser-engines.js
src/parser-os.js
src/parser-platforms.js
src/parser.js
src/utils.js

In order to support loading Bowser directly in the browser without transpilation this PR :
* Adds _.js_ file extensions to imports.
* Adds ES6 style export to utils and changes related utils imports
* Updates eslint rule for import extensions
Unit tests appear to need no changes as functionality is the same.
**Some thoughts**
As utils.js is a class collection of static functions it might be better the split them into a set of separate exports. This would mean imports could look like they are in the current master branch:
```Javascript
import { getFirstMatch, getSecondMatch, } from './utils.js';
```
rather than importing the whole of Utils.

Add file extensions to imports

---

README.md

Clarify use case in doc

---

index.d.ts

You could not use any of the Parser types in your own TS files.
- Export the types as part of the Bowser namespace
```
import Bowser from 'bowser'
// import * as Bowser from 'bowser' also works
const parsedResults: Bowser.Parser.ParsedResults = Bowser.parse(...);
```

Export Parser types

---

src/parser-browsers.js
test/acceptance/useragentstrings.yml

Hi @lancedikson,
First of all, thanks for the awesome module!
Second, I was trying to set a custom user-agent for my iOS app `iOSApp/3.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X)` and right now the result is `browser.name = iOSApp` and `browser.version = 3.0 (iPad; CPU iPhone OS 12_1_4 like Mac OS`. 
I noticed that this is happening because of the regexp on `parser-browser.js:594-595`, so I came up with a slightly different regexp to get the correct data. With this, I was able to get `browser.name = iOSApp` and `browser.version = 3.0`. 
```
Browser name: iOSApp
Browser version: 3.0
OS name: iOS
OS version: 12.1.4
Platform type: mobile
Platform vendor: Apple
Engine name: undefined
```
I hope this could help many other people as well :)

Update the regexp for generic browsers

---

src/bowser.js
src/constants.js
src/parser-engines.js
src/parser-os.js
src/parser-platforms.js
src/parser.js
src/utils.js
test/unit/parser.js

Now you can use it like this, and all tests have passed.
```javascript
import Bowser from 'bowser';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 OPR/43.0.2442.1165';
const parser = new Parser(UA, true);
parser.is(Bowser.OS_MAP.MacOS) === true
```
Most of the time when using bowser, we need to query alias mapping many times, which can solve this problem very well and make use of IDE's automatic completion.
It's time to say goodbye to the alias.

Add constant output so that users can quickly get all types

---

src/constants.js
src/parser-os.js
src/parser-platforms.js
test/acceptance/useragentstrings.yml

https://en.wikipedia.org/wiki/Roku#Software
examples: http://www.webapps-online.com/online-tools/user-agent-strings/dv/brand798903/roku-dvp
note: The reason I added the test for Roku before all other tests is that Roku user agents might contain other tokens (like Windows), but Roku is still Roku.

adding detection for Roku OS

---

package.json

> Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.

Update package.json to point to "types"

---

package.json

The 'module' field is used by bundlers such as rollup and webpack to determine the entrypoint for a package. Conventionally 'module' is used for the ES6 entrypoint, and 'main' is used for the CommonJS entrypoint.
Adding a 'module' field allows importing bowser as an ES6 module directly, rather than using a package-relative path to the ES6 entrypoint (e.g. `bowser/src/bowser`)
Closes #353

Add 'module' field to manifest

---

src/parser-os.js
src/parser-platforms.js
test/acceptance/useragentstrings.yml

This one's a little tricky, since it pretends to be desktop Safari for some reason.
See issue #378.

Correctly detect Firefox on iPad

---

index.d.ts
src/bowser.js

This PR adds the exposed maps to the types definition.
Also exports directly, but that change can be reverted.

fix: update types to include constants in types.d.ts

---

index.d.ts

There is no definition for `isBrowser` method within Parser class.
```javascript
Property 'isBrowser' does not exist on type 'Parser'
```
This PR is for fixing this issue.

added type definition for `isBrowser` in Parser Class

---

index.d.ts

[`getBrowserName`](https://github.com/lancedikson/bowser/blob/a990b6b2f63b8eb8dc686c6f5f0c8d71e66e9ae0/src/parser.js#L124) has `toLowerCase` option but it is lacked on typing

add toLowerCase option to getBrowserName in typing

---

src/parser-os.js
src/parser-platforms.js
test/acceptance/useragentstrings.yml

Should fix this issue: https://github.com/lancedikson/bowser/issues/401

handle Firefox on iPad on iOS 13

---

src/parser-browsers.js
test/acceptance/useragentstrings.yml

This adds support for detecting Xiaomi MiuiBrowser requested in #433 
```
// window.navigator.userAgent is:
// "Mozilla/5.0 (Linux; U; Android 9; fr-fr; Redmi Note 8 Pro Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML like Gecko) Version/4.0 Chrome/71.0.3578.141 Mobile Safari/537.36 XiaoMi/MiuiBrowser/11.9.3-"
const Bowser = require("bowser");
console.log(Bowser.parse(window.navigator.userAgent));
```
outputs
```
{
browser: { name: 'Miui', version: '11.9.3' },
os: { name: 'Android', version: '9', versionName: 'Pie' },
platform: { type: 'mobile' },
engine: { name: 'Blink' }
}
```

feat(browser): add detection for Miui Browser

---

src/parser.js
test/unit/parser.js

This adds support for using aliases in the `parser.is` method.
Requested in #389 
```
// window.navigation.userAgent is:
// "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
const Bowser = require("bowser");
console.log(Bowser.getParser(window.navigation.userAgent).is('edge', true));
```
outputs
```
true
```

feat: add support for using alias in 'is' method

---

index.d.ts

The method getEngineName exists both in the project and the official docs. It's just missing in the typescript declaration file.

Add missing typescript property declaration

---

index.d.ts

Bowser doesn't actually export methods as named exports, they are only destructured from the `Bowser` class. The types should reflect this.
This can be seen here tripping people up:
https://github.com/aws/aws-sdk-js-v3/pull/1991

Correct default export in type definitions

---

README.md
src/constants.js
src/parser-platforms.js

The [main docs](https://github.com/bowser-js/bowser#browser-names-for-satisfies) link to full list of aliases available in [`constants.js`](https://github.com/bowser-js/bowser/blob/master/src/constants.js). Now, the platforms defined there are incomplete since `Googlebot` is detected as a `bot` platform.

Add `bot` as a platform
