bowser-js/bowser

src/bowser.js
src/useragents.js

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
see 14.43

Parse user agent by default according to spec.

---

src/bowser.js

Add a function for test if the current browser is in the list of functions.

Add bowser test function.

---

README.md
src/bowser.js
src/useragents.js

This PR adds support for Microsoft Edge.
If you'd like the regexes tightened up, like using word boundary checks, just let me know.

Add support for Microsoft Edge.

---

src/bowser.js
test/test.js

Add browser unsupported browser check

---

typings.d.ts

isUnsupportedBrowser is missing in typings description

add isUnsupportedBrowser in typings

---

src/bowser.js

Unlikely to happen, but React Native.

Act safe in case navigator doesn't have a userAgent.

---

src/bowser.js
src/useragents.js

Added tests and support to detect Samsung Internet for Android

Added support for Samsung Internet for Android

---

typings.d.ts

fix(typings): add mobile and tablet flags

---

README.md

Hey, I found Bowser really useful. I needed a C# version, so I ported it. I added it to the read me in case anyone else also needed it. Thanks.

Add similar projects to README.md

---

README.md

`ded/bowser` repo doesn't exist on travis. hopefully, tests are really executed for this repository at  https://travis-ci.org/lancedikson/bowser :) 🎉

Fixes travis badge to point to right repository owner

---

README.md
src/parser.js
src/utils.js
test/unit/parser.js
test/unit/utils.js

I hope you guys can accept this, as it vastly improves usefulness in particular scenarios.

Adds loose comparison support

---

src/parser-browsers.js
test/acceptance/useragentstrings.yml

Hello, world;
This change adds Maxthon desktop browser detection.
I hope you like it 🙏.

Added Maxthon desktop support

---

CONTRIBUTING.md
README.md

Consolidate contribution instructions

Move contribution instructions from README to CONTRIBUTING

---

src/parser-os.js
test/acceptance/useragentstrings.yml

This patch detects Chrome OS as an operating system

Add operating system detection for Chrome OS

---

src/parser-os.js
src/utils.js
test/acceptance/useragentstrings.yml
test/unit/utils.js

Add "Pie" as version name for Android 9 and add version names to macOS.

Update OS version names

---

src/parser-os.js
test/acceptance/useragentstrings.yml

add windowswechat ua

---

src/parser.js
src/utils.js
test/unit/utils.js

#359 
* Added Array.prototype.find and Object.assign polyfills
* Utilised polyfills in place of native functions
* Added tests for utils.js
* Fixed some typos and linting errors

fixes #359 IE11 Added Array.prototype.find and Object.assign polyfills

---

.npmignore

Listed a few files and folders which are currently included in the published npm package, while they should not be.

Exclude unnecessary files from the npm package

---

src/parser-platforms.js
src/utils.js
test/acceptance/useragentstrings.yml

Added Nokia as vendor and Android 10 ("Q") as version name.
(Fix for issue #446 and issue #413)

Nokia Vendor

---

README.md

docs page has moved but link is not changed 🙏

Fix link to doc page on README.md

---

README.md

These PR removes links to sections that no longer exist in the README.md

Remove artifact links from README
